// src/redux/Types.js

export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const REMOVE_AUTH_TOKEN = 'REMOVE_AUTH_TOKEN';
export const SET_LOGGED_IN = 'SET_LOGGED_IN';
export const SET_IS_ADMIN = 'SET_IS_ADMIN';
export const SET_EMAIL = 'RERENDER_DASHBOARD'
export const SET_CURRENT_ACCOUNT = 'SET_CURRENT_ACCOUNT';
export const RERENDER_DASHBOARD = 'RERENDER_DASHBOARD'
export const RERENDER_CHAT_PANEL = 'RERENDER_CHAT_PANEL'

