// src/redux/Types.js

export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const REMOVE_AUTH_TOKEN = 'REMOVE_AUTH_TOKEN';
export const SET_LOGGED_IN = 'SET_LOGGED_IN';
export const SET_IS_ADMIN = 'SET_IS_ADMIN';
export const SET_EMAIL = 'RERENDER_DASHBOARD'
export const SET_CURRENT_ACCOUNT = 'SET_CURRENT_ACCOUNT';
export const RERENDER_DASHBOARD = 'RERENDER_DASHBOARD'
export const RERENDER_CHAT_PANEL = 'RERENDER_CHAT_PANEL'
export const RERENDER_RIGHT_PANEL = 'RERENDER_RIGHT_PANEL'
export const TEMPORARY_MESSAGE = 'TEMPORARY_MESSAGE'
export const SET_FACEBOOK_STATE = 'SET_FACEBOOK_STATE'
export const SET_IS_FB_SETUP = 'SET_IS_FB_SETUP'
export const OPEN_INTEGRATIONS_MODAL = 'OPEN_INTEGRATIONS_MODAL'
export const SET_FB_CODE = 'SET_FB_CODE'
export const IS_INTEGRATIONS_MODAL_CLOSED_BY_USER = 'IS_INTEGRATIONS_MODAL_CLOSED_BY_USER'
export const SELECT_PRODUCT_SERVICE_MODE = 'SELECT_PRODUCT_SERVICE_MODE'

